version: 3.0.0.{build}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: >-
    nuget restore

    $mainProjectFile = "$env:appveyor_build_folder\EasyAzureStorage\EasyAzureStorage.csproj"
    
    $mainProjectXml = [xml](get-content $mainProjectFile)
    
    $propertyGroup = $mainProjectXml.Project.PropertyGroup | Where { $_.PackageVersion}
    
    $propertyGroup.PackageVersion = $env:appveyor_build_version
    
    $mainprojectXml.Save($mainProjectFile)
    
    msbuild $mainProjectFile /t:pack /p:Configuration=Release
    
artifacts:
- path: '**\*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
  skip_symbols: true